package net.chuck.chucksmod.block.entity.tiers;

public interface TitaniumTier {
    int WIRE_TRANSFER_RATE = 512;
    int MAX_INSERT_EXTRACT = 256;
    int LOW_USAGE = 32;
    int MEDIUM_USAGE = 64;
    int HIGH_USAGE = 128;
    int GENERATION = MAX_INSERT_EXTRACT;
    int GEN_MAX_EXTRACT = GENERATION;
    int MACHINE_ENERGY_STORAGE = 40000;
    int ENERGY_STORAGE = 5*MACHINE_ENERGY_STORAGE;
    int ENERGY_STORAGE_INSERT_EXTRACT = 2*MAX_INSERT_EXTRACT;
    int SPEED = 150;
    int QUARRY_INV_SIZE = 16;
    int QUARRY_SIZE = 9;
    int QUARRY_SPEED = SPEED / 10;
    int FLUID_TANK_BUCKETS = 16;
    int MACHINE_BUCKET_STORAGE = 4;
    int XP_DRAIN_RATE = 100;
    int PUMP_SIZE = 2*QUARRY_SIZE-1;
    int PUMP_SPEED = SPEED/15;
    int FLUID_PIPE_TRANSFER_RATE = 200;
    int HARVESTER_SEEDS_INV_SIZE = 4;
    int HARVESTER_CROPS_INV_SIZE = 10;
    int HARVESTER_INV_SIZE = HARVESTER_SEEDS_INV_SIZE + HARVESTER_CROPS_INV_SIZE;
}
